# Generated by Django 6.0.3 on 2026-03-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Registra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.IntegerField()),
                ('name', models.CharField(max_length=23)),
                ('email', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.IntegerField()),
                ('name', models.CharField(max_length=27)),
                ('email', models.CharField()),
            ],
        ),
    ]
