# Generated by Django 6.0.2 on 2026-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AITS', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='aits_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('hod', 'Head of Department'), ('registrar', 'Academic Registrar')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='aits_users', to='auth.permission'),
        ),
    ]
